import type { IntegrationProvider } from '../../types';

const fitness = ['steps', 'active_energy_kcal', 'workout_minutes', 'workout', 'resting_heart_rate_bpm'] as const;
const sleep = ['sleep_duration_hours', 'sleep_score', 'sleep_latency_minutes', 'hrv_ms', 'recovery_score'] as const;
const body = ['weight_kg', 'body_fat_percent'] as const;
const nutrition = ['calorie_adherence_percent', 'macro_quality_score', 'meal_quality_score', 'hydration_liters'] as const;
const mental = ['mood_score', 'stress_score', 'therapy_session'] as const;
const mindfulness = ['meditation_minutes', 'mood_score', 'stress_score'] as const;

export const INTEGRATION_PROVIDERS: IntegrationProvider[] = [
  { id: 'apple-health', name: 'Apple Health', category: 'fitness', mode: 'device', description: 'Workouts, activity, sleep, mindfulness, vitals and body measurements from HealthKit.', dataTypes: [...fitness, ...sleep, ...body, 'meditation_minutes', 'spo2_percent'], permissions: ['Selected HealthKit read types'], nativeOnly: true, accent: '#FF3B30' },
  { id: 'health-connect', name: 'Android Health Connect', category: 'fitness', mode: 'device', description: 'Android health hub for activity, sleep, nutrition, mindfulness, vitals and medical records.', dataTypes: [...fitness, ...sleep, ...nutrition, ...body, 'meditation_minutes'], permissions: ['Selected Health Connect read permissions'], nativeOnly: true, accent: '#34A853' },
  { id: 'samsung-health', name: 'Samsung Health', category: 'fitness', mode: 'partner', description: 'Samsung activity, sleep and wellness data through the native Data SDK.', dataTypes: [...fitness, ...sleep, ...body], permissions: ['Samsung Health user consent'], nativeOnly: true, partnerApproval: true, accent: '#2274E0' },
  { id: 'fitbit', name: 'Fitbit', category: 'fitness', mode: 'oauth', description: 'Activity, workouts, sleep, heart rate and body measurements.', dataTypes: [...fitness, ...sleep, ...body], permissions: ['activity', 'heartrate', 'sleep', 'weight'], oauthReady: true, accent: '#00B0B9' },
  { id: 'garmin', name: 'Garmin Connect', category: 'fitness', mode: 'partner', description: 'Steps, workouts, sleep, stress, Body Battery, Pulse Ox and body composition.', dataTypes: [...fitness, ...sleep, ...body, 'stress_score', 'spo2_percent'], permissions: ['Garmin Connect Health API access'], partnerApproval: true, accent: '#00A9E0' },
  { id: 'polar', name: 'Polar Flow', category: 'fitness', mode: 'oauth', description: 'Training, daily activity, sleep and recovery through Polar AccessLink.', dataTypes: [...fitness, ...sleep], permissions: ['accesslink.read_all'], oauthReady: true, accent: '#D71920' },
  { id: 'whoop', name: 'WHOOP', category: 'fitness', mode: 'oauth', description: 'Cycles, strain, recovery, sleep, workouts and body measurements.', dataTypes: [...fitness, ...sleep, ...body], permissions: ['read:recovery', 'read:cycles', 'read:sleep', 'read:workout', 'read:body_measurement'], oauthReady: true, accent: '#44FF00' },
  { id: 'oura', name: 'Oura Ring', category: 'sleep', mode: 'oauth', description: 'Daily sleep, readiness, activity, heart rate, sessions and workouts.', dataTypes: [...fitness, ...sleep, 'meditation_minutes'], permissions: ['daily', 'heartrate', 'workout', 'session'], oauthReady: true, accent: '#B9A7FF' },
  { id: 'strava', name: 'Strava', category: 'fitness', mode: 'oauth', description: 'Running, cycling and other recorded activities.', dataTypes: ['workout', 'workout_minutes', 'active_energy_kcal'], permissions: ['activity:read_all'], oauthReady: true, accent: '#FC4C02' },
  { id: 'withings', name: 'Withings', category: 'medical', mode: 'oauth', description: 'Body composition, activity, sleep, blood pressure and other connected measurements.', dataTypes: [...fitness, ...sleep, ...body, 'blood_pressure_systolic', 'blood_pressure_diastolic'], permissions: ['user.info', 'user.metrics', 'user.activity'], oauthReady: true, accent: '#00A3E0' },
  { id: 'suunto', name: 'Suunto', category: 'fitness', mode: 'partner', description: 'Outdoor workouts, routes and daily activity.', dataTypes: [...fitness], permissions: ['Suunto partner access'], partnerApproval: true, accent: '#E31B23' },
  { id: 'wahoo', name: 'Wahoo', category: 'fitness', mode: 'oauth', description: 'Cycling, running and indoor workout history.', dataTypes: ['workout', 'workout_minutes', 'active_energy_kcal'], permissions: ['Workout history'], accent: '#54C571' },
  { id: 'coros', name: 'COROS', category: 'fitness', mode: 'file', description: 'Import COROS workout exports.', dataTypes: ['workout', 'workout_minutes', ...sleep], permissions: ['Selected export file'], accent: '#FF6B00' },
  { id: 'zwift', name: 'Zwift', category: 'fitness', mode: 'file', description: 'Import indoor cycling and running activities.', dataTypes: ['workout', 'workout_minutes', 'active_energy_kcal'], permissions: ['Selected export file'], accent: '#F36C21' },
  { id: 'peloton', name: 'Peloton', category: 'fitness', mode: 'file', description: 'Import cycling, running, strength and class history.', dataTypes: ['workout', 'workout_minutes', 'active_energy_kcal'], permissions: ['Selected export file'], accent: '#DF1C2F' },
  { id: 'eight-sleep', name: 'Eight Sleep', category: 'sleep', mode: 'file', description: 'Import sleep duration, quality, HRV and recovery values.', dataTypes: [...sleep], permissions: ['Selected export file'], accent: '#6D5DFC' },
  { id: 'sleep-cycle', name: 'Sleep Cycle', category: 'sleep', mode: 'file', description: 'Import sleep duration, quality and latency.', dataTypes: ['sleep_duration_hours', 'sleep_score', 'sleep_latency_minutes'], permissions: ['Selected export file'], accent: '#5B7FFF' },
  { id: 'autosleep', name: 'AutoSleep', category: 'sleep', mode: 'file', description: 'Import Apple Watch sleep and recovery history.', dataTypes: [...sleep], permissions: ['Selected export file'], accent: '#4ECDC4' },
  { id: 'pillow', name: 'Pillow', category: 'sleep', mode: 'file', description: 'Import sleep session history and quality.', dataTypes: ['sleep_duration_hours', 'sleep_score', 'sleep_latency_minutes'], permissions: ['Selected export file'], accent: '#7B61FF' },
  { id: 'myfitnesspal', name: 'MyFitnessPal', category: 'nutrition', mode: 'file', description: 'Import calories, macros, meal quality and hydration.', dataTypes: [...nutrition], permissions: ['Selected export file'], accent: '#0066EE' },
  { id: 'cronometer', name: 'Cronometer', category: 'nutrition', mode: 'file', description: 'Import nutrition adherence, macro quality and hydration.', dataTypes: [...nutrition, 'weight_kg'], permissions: ['Selected export file'], accent: '#FFB000' },
  { id: 'yazio', name: 'YAZIO', category: 'nutrition', mode: 'file', description: 'Import diary, calorie target and nutrition summaries.', dataTypes: [...nutrition, 'weight_kg'], permissions: ['Selected export file'], accent: '#FF5C35' },
  { id: 'lifesum', name: 'Lifesum', category: 'nutrition', mode: 'file', description: 'Import food diary, water and nutrition scores.', dataTypes: [...nutrition], permissions: ['Selected export file'], accent: '#68C455' },
  { id: 'lose-it', name: 'Lose It!', category: 'nutrition', mode: 'file', description: 'Import calorie, meal and weight history.', dataTypes: [...nutrition, 'weight_kg'], permissions: ['Selected export file'], accent: '#F05A47' },
  { id: 'macrofactor', name: 'MacroFactor', category: 'nutrition', mode: 'file', description: 'Import nutrition adherence and body-weight trends.', dataTypes: ['calorie_adherence_percent', 'macro_quality_score', 'weight_kg'], permissions: ['Selected export file'], accent: '#7756FF' },
  { id: 'foodnoms', name: 'FoodNoms', category: 'nutrition', mode: 'file', description: 'Import calorie, macro and hydration logs.', dataTypes: [...nutrition], permissions: ['Selected export file'], accent: '#FF8C42' },
  { id: 'noom', name: 'Noom', category: 'nutrition', mode: 'file', description: 'Import nutrition and weight tracking summaries.', dataTypes: ['meal_quality_score', 'weight_kg', 'mood_score'], permissions: ['Selected export file'], accent: '#FF5A5F' },
  { id: 'daylio', name: 'Daylio', category: 'mental', mode: 'file', description: 'Import mood and activity diary history.', dataTypes: ['mood_score', 'stress_score'], permissions: ['Selected export file'], accent: '#8A7CFF' },
  { id: 'bearable', name: 'Bearable', category: 'mental', mode: 'file', description: 'Import mood, symptoms, stress, sleep and lifestyle factors.', dataTypes: [...mental, ...sleep], permissions: ['Selected export file'], accent: '#8860D0' },
  { id: 'minddoc', name: 'MindDoc', category: 'mental', mode: 'file', description: 'Import private mood and mental-wellbeing history.', dataTypes: ['mood_score', 'stress_score'], permissions: ['Selected export file'], accent: '#00A99D' },
  { id: 'headspace', name: 'Headspace', category: 'mindfulness', mode: 'file', description: 'Import meditation practice history.', dataTypes: ['meditation_minutes'], permissions: ['Selected export file'], accent: '#F47D31' },
  { id: 'calm', name: 'Calm', category: 'mindfulness', mode: 'file', description: 'Import meditation and sleep-session history.', dataTypes: ['meditation_minutes', 'sleep_duration_hours'], permissions: ['Selected export file'], accent: '#3A8DDE' },
  { id: 'insight-timer', name: 'Insight Timer', category: 'mindfulness', mode: 'file', description: 'Import meditation sessions and duration.', dataTypes: ['meditation_minutes'], permissions: ['Selected export file'], accent: '#00A6A6' },
  { id: 'waking-up', name: 'Waking Up', category: 'mindfulness', mode: 'file', description: 'Import meditation practice history.', dataTypes: ['meditation_minutes'], permissions: ['Selected export file'], accent: '#E7B44A' },
  { id: 'medito', name: 'Medito', category: 'mindfulness', mode: 'file', description: 'Import meditation practice history.', dataTypes: ['meditation_minutes'], permissions: ['Selected export file'], accent: '#4B6BFB' },
  { id: 'dexcom', name: 'Dexcom', category: 'medical', mode: 'oauth', description: 'Import authorized continuous glucose monitoring observations.', dataTypes: ['glucose_mg_dl'], permissions: ['offline_access'], oauthReady: true, partnerApproval: true, accent: '#00A651' },
  { id: 'freestyle-libre', name: 'FreeStyle Libre', category: 'medical', mode: 'partner', description: 'Glucose observations through approved Libre partner access or export.', dataTypes: ['glucose_mg_dl'], permissions: ['Libre user consent'], partnerApproval: true, accent: '#FFD100' },
  { id: 'fhir', name: 'FHIR R4 Health Record', category: 'medical', mode: 'fhir', description: 'Standards-based observation import from a compatible health provider.', dataTypes: ['glucose_mg_dl', 'blood_pressure_systolic', 'blood_pressure_diastolic', 'weight_kg', 'spo2_percent'], permissions: ['FHIR Observation read access'], accent: '#E56B6F' },
  { id: 'rescuetime', name: 'RescueTime', category: 'productivity', mode: 'file', description: 'Import focused and productive time.', dataTypes: ['focus_minutes'], permissions: ['Selected export file'], accent: '#3F8EFC' },
  { id: 'toggl', name: 'Toggl Track', category: 'productivity', mode: 'file', description: 'Import focused work duration.', dataTypes: ['focus_minutes'], permissions: ['Selected export file'], accent: '#E57CD8' },
  { id: 'generic-csv', name: 'Universal CSV / JSON', category: 'generic', mode: 'file', description: 'Import any supported metric using the open ARETUNE event format.', dataTypes: [...fitness, ...sleep, ...body, ...nutrition, ...mental, ...mindfulness, 'focus_minutes', 'glucose_mg_dl'], permissions: ['Selected local file only'], accent: '#C9A84C' },
  { id: 'generic-webhook', name: 'Personal Webhook', category: 'generic', mode: 'webhook', description: 'Receive normalized events from automations such as Shortcuts, Zapier or Make.', dataTypes: [...fitness, ...sleep, ...nutrition, ...mental, 'meditation_minutes', 'focus_minutes'], permissions: ['Revocable personal webhook token'], accent: '#9CA3AF' },
];

export const INTEGRATION_CATEGORIES = [
  { id: 'all', label: 'All' }, { id: 'fitness', label: 'Fitness' }, { id: 'nutrition', label: 'Nutrition' },
  { id: 'mental', label: 'Mental health' }, { id: 'sleep', label: 'Sleep' },
  { id: 'mindfulness', label: 'Mindfulness' }, { id: 'medical', label: 'Medical' },
  { id: 'productivity', label: 'Focus' }, { id: 'generic', label: 'Universal' },
] as const;

export const providerById = (id: string) => INTEGRATION_PROVIDERS.find((provider) => provider.id === id);
